---
- hosts: dockerhost

  tasks:
  - name: stop existing container
    command: docker stop myapp
    ignore_errors: yes
  - name: remove container
    command: docker rm myapp
    ignore_errors: yes
  - name:     remove image
    command: docker rmi imamit13/capstone:latest
    ignore_errors: yes
  - name:     create container
    command: docker run -d --name myapp -p 8082:8080 imamit13/capstone:latest
    ignore_errors: yes
